In [10]:
#Importing necessary packages
import numpy as np
import pandas as pd
from plotnine import *
from janitor import *
import matplotlib.pyplot as plt
from lets_plot import *
LetsPlot.setup_html(no_js=True)

In [11]:
#Loading the 1854-1855 dataset and checking the entries
data_1854_1855 = pd.read_excel('raw_night_1854_1855.xlsx')
data_1854_1855.head(12)

       Month  Avg Army Size  Disease Deaths  Wounds  Other Causes
0   Apr 1854           8571               1       0             5
1   May 1854          23333              12       0             9
2   Jun 1854          28333              11       0             6
3   Jul 1854          28722             359       0            23
4   Aug 1854          30246             828       1            30
5   Sep 1854          30290             788      81            70
6   Oct 1854          30643             503     132           128
7   Nov 1854          27543             844     287           106
8   Dec 1854          32393            1725     114           131
9   Jan 1855          32393            2761      83           324
10  Feb 1855          30460            2120      42           361
11  Mar 1855          32393            1207      32           172

In [12]:
#Loading the 1855-1856 dataset and checking the entries
data_1855_1856 = pd.read_excel('raw_night_1855_1856.xlsx')
data_1855_1856.head(12)

       Month  Avg Army Size  Disease Deaths  Wounds  Other Causes
0   Apr 1855          32393             477      48            57
1   May 1855          35693             508      32            37
2   Jun 1855          40253             802      31            31
3   Jul 1855          35786             382      30            33
4   Aug 1855          51074             483      41            55
5   Sep 1855          52280             189      47            37
6   Oct 1855          53321             128      36            33
7   Nov 1855          45679             178      19            18
8   Dec 1855          36241              91      15            15
9   Jan 1856          34292              42       2             3
10  Feb 1856          34392              24       0             2
11  Mar 1856          36667              15       0             4

In [13]:
#Checking Information about the dataset
print(data_1854_1855.info())

print(data_1855_1856.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Month           12 non-null     object
 1   Avg Army Size   12 non-null     int64
 2   Disease Deaths  12 non-null     int64
 3   Wounds          12 non-null     int64
 4   Other Causes    12 non-null     int64
dtypes: int64(4), object(1)
memory usage: 612.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Month           12 non-null     object
 1   Avg Army Size   12 non-null     int64
 2   Disease Deaths  12 non-null     int64
 3   Wounds          12 non-null     int64
 4   Other Causes    12 non-null     int64
dtypes: int64(4), object(1)
memory usage: 612.0+ bytes
None

### Data Cleaning

In [14]:
#Transforming the data from wide to long
data_1854_1855 = data_1854_1855.pivot_longer(index = ['Month', 'Avg Army Size'],
                                             names_to = 'Cause of Death', 
                                             values_to = 'Number')
data_1854_1855

# Creating a new DataFrame with the Month Column splitted into Month and Year
data1 = pd.DataFrame(data_1854_1855['Month'].str.split(' ', expand= True))
# Renaming the new columns created 
data1 = data1.rename(columns={0: 'Month_2', 1: 'Year'})

# Joining the previous DataFrame with the new DataFrame
data_54 = pd.concat([data_1854_1855, data1], axis=1)

#Replacing the Entries to their full name
data_54['Month_2'] = data_54['Month_2'].replace(['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'], ['APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', 'JANUARY', 'FEBRUARY', 'MARCH'])
data_54['Number'] = data_54['Number'].astype('int')
data_54['Cause of Death'] = data_54['Cause of Death'].str.replace('Disease Deaths', 'Diseases')
data_54

       Month  Avg Army Size Cause of Death  Number    Month_2  Year
0   Apr 1854           8571       Diseases       1      APRIL  1854
1   May 1854          23333       Diseases      12        MAY  1854
2   Jun 1854          28333       Diseases      11       JUNE  1854
3   Jul 1854          28722       Diseases     359       JULY  1854
4   Aug 1854          30246       Diseases     828     AUGUST  1854
5   Sep 1854          30290       Diseases     788  SEPTEMBER  1854
6   Oct 1854          30643       Diseases     503    OCTOBER  1854
7   Nov 1854          27543       Diseases     844   NOVEMBER  1854
8   Dec 1854          32393       Diseases    1725   DECEMBER  1854
9   Jan 1855          32393       Diseases    2761    JANUARY  1855
10  Feb 1855          30460       Diseases    2120   FEBRUARY  1855
11  Mar 1855          32393       Diseases    1207      MARCH  1855
12  Apr 1854           8571         Wounds       0      APRIL  1854
13  May 1854          23333         Wounds       0        MAY  1854
14  Jun 1854          28333         Wounds       0       JUNE  1854
15  Jul 1854          28722         Wounds       0       JULY  1854
16  Aug 1854          30246         Wounds       1     AUGUST  1854
17  Sep 1854          30290         Wounds      81  SEPTEMBER  1854
18  Oct 1854          30643         Wounds     132    OCTOBER  1854
19  Nov 1854          27543         Wounds     287   NOVEMBER  1854
20  Dec 1854          32393         Wounds     114   DECEMBER  1854
21  Jan 1855          32393         Wounds      83    JANUARY  1855
22  Feb 1855          30460         Wounds      42   FEBRUARY  1855
23  Mar 1855          32393         Wounds      32      MARCH  1855
24  Apr 1854           8571   Other Causes       5      APRIL  1854
25  May 1854          23333   Other Causes       9        MAY  1854
26  Jun 1854          28333   Other Causes       6       JUNE  1854
27  Jul 1854          28722   Other Causes      23       JULY  1854
28  Aug 1854          30246   Other Causes      30     AUGUST  1854
29  Sep 1854          30290   Other Causes      70  SEPTEMBER  1854
30  Oct 1854          30643   Other Causes     128    OCTOBER  1854
31  Nov 1854          27543   Other Causes     106   NOVEMBER  1854
32  Dec 1854          32393   Other Causes     131   DECEMBER  1854
33  Jan 1855          32393   Other Causes     324    JANUARY  1855
34  Feb 1855          30460   Other Causes     361   FEBRUARY  1855
35  Mar 1855          32393   Other Causes     172      MARCH  1855

In [15]:
#Checking the Statistical description of the datasets
print(data_1854_1855.describe())

print(data_1855_1856.describe())

       Avg Army Size       Number
count      36.000000    36.000000
mean    27943.333333   369.333333
std      6422.886071   643.328843
min      8571.000000     0.000000
25%     28135.500000    10.500000
50%     30268.000000    94.500000
75%     31080.500000   359.500000
max     32393.000000  2761.000000
       Avg Army Size  Disease Deaths     Wounds  Other Causes
count      12.000000       12.000000  12.000000     12.000000
mean    40672.583333      276.583333  25.083333     27.083333
std      7753.075278      249.483998  17.619505     18.894243
min     32393.000000       15.000000   0.000000      2.000000
25%     35367.750000       78.750000  11.750000     12.250000
50%     36454.000000      183.500000  30.500000     32.000000
75%     47027.750000      478.500000  37.250000     37.000000
max     53321.000000      802.000000  48.000000     57.000000

### Visualising the Coxcomb plot for year 1854 - 1855

In [ ]:
# Creating the radius column which is the square root for better visualization
data_54['radius'] = np.sqrt(data_54['Number'])

#Transforming the Cause of Death column to categorical column
data_54['Cause of Death'] = pd.Categorical(data_54['Cause of Death'],
              categories = ["Wounds", "Other Causes", "Diseases"],
              ordered = True)

      Month_2  Year Cause of Death  Number     radius
0       APRIL  1854       Diseases       1   1.000000
1       APRIL  1854   Other Causes       5   2.236068
2       APRIL  1854         Wounds       0   0.000000
3      AUGUST  1854         Wounds       1   1.000000
4      AUGUST  1854       Diseases     828  28.774989
5      AUGUST  1854   Other Causes      30   5.477226
6    DECEMBER  1854   Other Causes     131  11.445523
7    DECEMBER  1854       Diseases    1725  41.533119
8    DECEMBER  1854         Wounds     114  10.677078
9    FEBRUARY  1855         Wounds      42   6.480741
10   FEBRUARY  1855   Other Causes     361  19.000000
11   FEBRUARY  1855       Diseases    2120  46.043458
12    JANUARY  1855       Diseases    2761  52.545219
13    JANUARY  1855   Other Causes     324  18.000000
14    JANUARY  1855         Wounds      83   9.110434
15       JULY  1854   Other Causes      23   4.795832
16       JULY  1854         Wounds       0   0.000000
17       JULY  1854       Diseases     359  18.947295
18       JUNE  1854         Wounds       0   0.000000
19       JUNE  1854       Diseases      11   3.316625
20       JUNE  1854   Other Causes       6   2.449490
21      MARCH  1855         Wounds      32   5.656854
22      MARCH  1855   Other Causes     172  13.114877
23      MARCH  1855       Diseases    1207  34.741906
24        MAY  1854         Wounds       0   0.000000
25        MAY  1854   Other Causes       9   3.000000
26        MAY  1854       Diseases      12   3.464102
27   NOVEMBER  1854       Diseases     844  29.051678
28   NOVEMBER  1854   Other Causes     106  10.295630
29   NOVEMBER  1854         Wounds     287  16.941074
30    OCTOBER  1854         Wounds     132  11.489125
31    OCTOBER  1854       Diseases     503  22.427661
32    OCTOBER  1854   Other Causes     128  11.313708
33  SEPTEMBER  1854   Other Causes      70   8.366600
34  SEPTEMBER  1854       Diseases     788  28.071338
35  SEPTEMBER  1854         Wounds      81   9.000000

In [17]:
p1 = (ggplot(data_54, aes('Month_2', 'radius', fill = 'Cause of Death')) 
 + geom_bar(stat='identity', width = 1, alpha = 0.8, color='grey') 
 + coord_polar(direction=1, start= -np.pi/2.4)
 + theme_minimal()
 + scale_fill_manual(values = ["#fb9a99", "grey30", "skyblue"]) 
+ labs(title = "Chart showing the Causes of Death in the Crimean War \nfrom APRIL 1854 - MARCH 1855") 
+ theme(axis_title_y = element_blank(),
        axis_title_x = element_blank(),
        axis_text_y = element_blank(),
        axis_ticks = element_blank(),
        plot_title = element_text(size=15, face='bold', hjust = 0.5),
        panel_grid = element_blank(),
        panel_border = element_blank(),
        legend_position='bottom')
+  ggsize(900, 600))
p1

#### 1855 - 1856 (Data Cleaning)

In [18]:
#Transforming the data from wide to long
data_1855_1856 = data_1855_1856.pivot_longer(index = ['Month', 'Avg Army Size'],
                                             names_to = 'Cause of Death', 
                                             values_to = 'Number')
data_1855_1856

# Creating a new DataFrame with the Month Column splitted into Month and Year
data1 = pd.DataFrame(data_1855_1856['Month'].str.split(' ', expand= True))
# Renaming the new columns created 
data1 = data1.rename(columns={0: 'Month_2', 1: 'Year'})

# Joining the previous DataFrame with the new DataFrame
data_55 = pd.concat([data_1855_1856, data1], axis=1)

#Replacing the Entries to their full name
data_55['Month_2'] = data_55['Month_2'].replace(['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'], ['APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', 'JANUARY', 'FEBRUARY', 'MARCH'])
data_55['Number'] = data_55['Number'].astype('int')
data_55['Cause of Death'] = data_55['Cause of Death'].str.replace('Disease Deaths', 'Diseases')
data_55

       Month  Avg Army Size Cause of Death  Number    Month_2  Year
0   Apr 1855          32393       Diseases     477      APRIL  1855
1   May 1855          35693       Diseases     508        MAY  1855
2   Jun 1855          40253       Diseases     802       JUNE  1855
3   Jul 1855          35786       Diseases     382       JULY  1855
4   Aug 1855          51074       Diseases     483     AUGUST  1855
5   Sep 1855          52280       Diseases     189  SEPTEMBER  1855
6   Oct 1855          53321       Diseases     128    OCTOBER  1855
7   Nov 1855          45679       Diseases     178   NOVEMBER  1855
8   Dec 1855          36241       Diseases      91   DECEMBER  1855
9   Jan 1856          34292       Diseases      42    JANUARY  1856
10  Feb 1856          34392       Diseases      24   FEBRUARY  1856
11  Mar 1856          36667       Diseases      15      MARCH  1856
12  Apr 1855          32393         Wounds      48      APRIL  1855
13  May 1855          35693         Wounds      32        MAY  1855
14  Jun 1855          40253         Wounds      31       JUNE  1855
15  Jul 1855          35786         Wounds      30       JULY  1855
16  Aug 1855          51074         Wounds      41     AUGUST  1855
17  Sep 1855          52280         Wounds      47  SEPTEMBER  1855
18  Oct 1855          53321         Wounds      36    OCTOBER  1855
19  Nov 1855          45679         Wounds      19   NOVEMBER  1855
20  Dec 1855          36241         Wounds      15   DECEMBER  1855
21  Jan 1856          34292         Wounds       2    JANUARY  1856
22  Feb 1856          34392         Wounds       0   FEBRUARY  1856
23  Mar 1856          36667         Wounds       0      MARCH  1856
24  Apr 1855          32393   Other Causes      57      APRIL  1855
25  May 1855          35693   Other Causes      37        MAY  1855
26  Jun 1855          40253   Other Causes      31       JUNE  1855
27  Jul 1855          35786   Other Causes      33       JULY  1855
28  Aug 1855          51074   Other Causes      55     AUGUST  1855
29  Sep 1855          52280   Other Causes      37  SEPTEMBER  1855
30  Oct 1855          53321   Other Causes      33    OCTOBER  1855
31  Nov 1855          45679   Other Causes      18   NOVEMBER  1855
32  Dec 1855          36241   Other Causes      15   DECEMBER  1855
33  Jan 1856          34292   Other Causes       3    JANUARY  1856
34  Feb 1856          34392   Other Causes       2   FEBRUARY  1856
35  Mar 1856          36667   Other Causes       4      MARCH  1856

### Visualising the Coxcomb plot for year 1855 - 1856

In [19]:
data_55['radius'] = np.sqrt(data_55['Number'])
data_55['Cause of Death'] = pd.Categorical(data_55['Cause of Death'], 
                                           categories=['Wounds', 'Other Causes', 'Diseases'],
                                           ordered = True)
data_55

       Month  Avg Army Size Cause of Death  Number    Month_2  Year     radius
0   Apr 1855          32393       Diseases     477      APRIL  1855  21.840330
1   May 1855          35693       Diseases     508        MAY  1855  22.538855
2   Jun 1855          40253       Diseases     802       JUNE  1855  28.319605
3   Jul 1855          35786       Diseases     382       JULY  1855  19.544820
4   Aug 1855          51074       Diseases     483     AUGUST  1855  21.977261
5   Sep 1855          52280       Diseases     189  SEPTEMBER  1855  13.747727
6   Oct 1855          53321       Diseases     128    OCTOBER  1855  11.313708
7   Nov 1855          45679       Diseases     178   NOVEMBER  1855  13.341664
8   Dec 1855          36241       Diseases      91   DECEMBER  1855   9.539392
9   Jan 1856          34292       Diseases      42    JANUARY  1856   6.480741
10  Feb 1856          34392       Diseases      24   FEBRUARY  1856   4.898979
11  Mar 1856          36667       Diseases      15      MARCH  1856   3.872983
12  Apr 1855          32393         Wounds      48      APRIL  1855   6.928203
13  May 1855          35693         Wounds      32        MAY  1855   5.656854
14  Jun 1855          40253         Wounds      31       JUNE  1855   5.567764
15  Jul 1855          35786         Wounds      30       JULY  1855   5.477226
16  Aug 1855          51074         Wounds      41     AUGUST  1855   6.403124
17  Sep 1855          52280         Wounds      47  SEPTEMBER  1855   6.855655
18  Oct 1855          53321         Wounds      36    OCTOBER  1855   6.000000
19  Nov 1855          45679         Wounds      19   NOVEMBER  1855   4.358899
20  Dec 1855          36241         Wounds      15   DECEMBER  1855   3.872983
21  Jan 1856          34292         Wounds       2    JANUARY  1856   1.414214
22  Feb 1856          34392         Wounds       0   FEBRUARY  1856   0.000000
23  Mar 1856          36667         Wounds       0      MARCH  1856   0.000000
24  Apr 1855          32393   Other Causes      57      APRIL  1855   7.549834
25  May 1855          35693   Other Causes      37        MAY  1855   6.082763
26  Jun 1855          40253   Other Causes      31       JUNE  1855   5.567764
27  Jul 1855          35786   Other Causes      33       JULY  1855   5.744563
28  Aug 1855          51074   Other Causes      55     AUGUST  1855   7.416198
29  Sep 1855          52280   Other Causes      37  SEPTEMBER  1855   6.082763
30  Oct 1855          53321   Other Causes      33    OCTOBER  1855   5.744563
31  Nov 1855          45679   Other Causes      18   NOVEMBER  1855   4.242641
32  Dec 1855          36241   Other Causes      15   DECEMBER  1855   3.872983
33  Jan 1856          34292   Other Causes       3    JANUARY  1856   1.732051
34  Feb 1856          34392   Other Causes       2   FEBRUARY  1856   1.414214
35  Mar 1856          36667   Other Causes       4      MARCH  1856   2.000000

In [20]:
p2 = (ggplot(data_55, aes('Month_2', 'radius', fill = 'Cause of Death')) 
 + geom_bar(stat='identity', width = 1, alpha = 0.6, color = 'grey') 
 + coord_polar(direction=1, start= -np.pi/2.4)
 + theme_minimal()
 + scale_fill_manual(values = ["#fb9a99", "grey30", "skyblue"]) 
+ labs(title = "Chart showing the Causes of Death in the Crimean War \nfrom APRIL 1855 - MARCH 1856") 
+ theme(axis_title_y = element_blank(),
        axis_title_x = element_blank(),
        axis_text_y = element_blank(),
        axis_ticks = element_blank(),
        plot_title = element_text(size=15, face='bold', hjust = 0.5),
        panel_grid = element_blank(),
        panel_border = element_blank(),
        legend_position='bottom')
+  ggsize(900, 600))
p2

In [21]:
gggrid([p2, p1], ncol = 2)

### Final Reflections
* The datasets are excel files with 12 entries and 5 columns each.

* There are no missing entries or duplicates

* From April 1854 - March 1855, the maximum & mean number of deaths was far more than that of April 1855 - March 1856.

* After visualising using a Coxcomb plot just as Florence Nightingale did, i was able to see that deaths from April 1854 - March 1855 were mostly caused by **diseases** but the number reduced the next year.

* This suggest that the solution Florence Nightingale proposed worked.